#!/usr/bin/env python3

# TODO
import os
import sys

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # analyze word
    screen_name = sys.argv[1]
    tweets = get_user_timeline(screen_name, count=50)
    if tweets == None:
        sys.exit
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored('{score} {tweet}'.format(score = score, tweet = tweet), "green"))
        elif score < 0.0:
            print(colored('{score} {tweet}'.format(score = score, tweet = tweet), "red"))
        else:
            print(colored('{score} {tweet}'.format(score = score, tweet = tweet), "yellow"))

if __name__ == "__main__":
    main()
